---
- name: Security Policies
  win_security_policy:
    section: System Access
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
  - { rule: 1.1.1, key: PasswordHistorySize, value: 24 }
  - { rule: 1.1.2, key: MaximumPasswordAge, value: 60 }
  - { rule: 1.1.3, key: MinimumPasswordAge, value: 1 }
  - { rule: 1.1.4, key: MinimumPasswordLength, value: 14 }
  - { rule: 1.1.5, key: PasswordComplexity, value: 1 }
  - { rule: 1.1.6, key: ClearTextPassword, value: 0 }
  - { rule: 1.2.2, key: LockoutBadCount, value: 10 }
  - { rule: 1.2.3, key: ResetLockoutCount, value: 0 }
  - { rule: 1.2.1, key: LockoutDuration, value: 900 }
