---
- name: Domain Firewall
  win_regedit:
    path: 'HKLM:\Software\Policies\Microsoft\WindowsFirewall\DomainProfile'
    name: "{{ item.name }}"
    data: "{{ item.data }}"
    type: "{{ item.type }}"
    state: present
  with_items:
  - { rule: 9.1.1, name: EnableFirewall, data: 1, type: dword }
  - { rule: 9.1.2, name: DefaultInboundAction, data: 1, type: dword }
  - { rule: 9.1.3, name: DefaultOutboundAction, data: 0, type: dword }
  - { rule: 9.1.4, name: DisableNotifications, data: 1, type: dword }
  - { rule: 9.1.5, name: AllowLocalPolicyMerge, data: 1, type: dword }
  - { rule: 9.1.6, name: AllowLocalIPsecPolicyMerge, data: 1, type: dword }

- name: Domain Firewall Logging
  win_regedit:
    path: 'HKLM:\Software\Policies\Microsoft\WindowsFirewall\DomainProfile\Logging'
    name: "{{ item.name }}"
    data: "{{ item.data }}"
    type: "{{ item.type }}"
    state: present
  with_items:
  - { rule: 9.1.7, name: LogFilePath, data: '%SYSTEMROOT%\System32\logfiles\firewall\domainfw.log', type: string }
  - { rule: 9.1.8, name: LogFileSize, data: 16384, type: dword }
  - { rule: 9.1.9, name: LogDroppedPackets, data: 1, type: dword }
  - { rule: 9.1.10, name: LogSuccessfulConnections, data: 1, type: dword }

- name: Private Firewall
  win_regedit:
    path: 'HKLM:\Software\Policies\Microsoft\WindowsFirewall\PrivateProfile'
    name: "{{ item.name }}"
    data: "{{ item.data }}"
    type: "{{ item.type }}"
    state: present
  with_items:
  - { rule: 9.2.1, name: EnableFirewall, data: 1, type: dword }
  - { rule: 9.2.2, name: DefaultInboundAction, data: 1, type: dword }
  - { rule: 9.2.3, name: DefaultOutboundAction, data: 0, type: dword }
  - { rule: 9.2.4, name: DisableNotifications, data: 1, type: dword }
  - { rule: 9.2.5, name: AllowLocalPolicyMerge, data: 1, type: dword }
  - { rule: 9.2.6, name: AllowLocalIPsecPolicyMerge, data: 1, type: dword }

- name: Private Firewall Logging
  win_regedit:
    path: 'HKLM:\Software\Policies\Microsoft\WindowsFirewall\PrivateProfile\Logging'
    name: "{{ item.name }}"
    data: "{{ item.data }}"
    type: "{{ item.type }}"
    state: present
  with_items:
  - { rule: 9.2.7, name: LogFilePath, data: '%SYSTEMROOT%\System32\logfiles\firewall\privatefw.log', type: string }
  - { rule: 9.2.8, name: LogFileSize, data: 16384, type: dword }
  - { rule: 9.2.9, name: LogDroppedPackets, data: 1, type: dword }
  - { rule: 9.2.10, name: LogSuccessfulConnections, data: 1, type: dword }

- name: Public Firewall
  win_regedit:
    path: 'HKLM:\Software\Policies\Microsoft\WindowsFirewall\PublicProfile'
    name: "{{ item.name }}"
    data: "{{ item.data }}"
    type: "{{ item.type }}"
    state: present
  with_items:
  - { rule: 9.3.1, name: EnableFirewall, data: 1, type: dword }
  - { rule: 9.3.2, name: DefaultInboundAction, data: 1, type: dword }
  - { rule: 9.3.3, name: DefaultOutboundAction, data: 0, type: dword }
  - { rule: 9.3.4, name: DisableNotifications, data: 0, type: dword }
  - { rule: 9.3.5, name: AllowLocalPolicyMerge, data: 0, type: dword }
  - { rule: 9.3.6, name: AllowLocalIPsecPolicyMerge, data: 0, type: dword }

- name: Public Firewall Logging
  win_regedit:
    path: 'HKLM:\Software\Policies\Microsoft\WindowsFirewall\PublicProfile\Logging'
    name: "{{ item.name }}"
    data: "{{ item.data }}"
    type: "{{ item.type }}"
    state: present
  with_items:
  - { rule: 9.3.7, name: LogFilePath, data: '%SYSTEMROOT%\System32\logfiles\firewall\publicfw.log', type: string }
  - { rule: 9.3.8, name: LogFileSize, data: 16384, type: dword }
  - { rule: 9.3.9, name: LogDroppedPackets, data: 1, type: dword }
  - { rule: 9.3.10, name: LogSuccessfulConnections, data: 1, type: dword }
